import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import EventGrid from "../components/EventGrid";
import axios from "axios";
import { useState, useEffect } from "react";

export default function Home() {
  const [dateSplitEvents, setDateSplitEvents] = useState({});

  useEffect(() => {
    getAllEvents();
  }, []);

  const getAllEvents = async () => {
    axios.get("/api/events").then((response) => {
      const allEvents = response.data.events;
      const tempDateSplitEvents = {};
      allEvents.map((event) => {
        // if date does not already have events tied to it, create a new key-val pair with the new event as the single element in the list
        if (!(event.date in tempDateSplitEvents)) {
          tempDateSplitEvents[event.date] = [
            {
              venue: event.venue,
              link: event.link,
              description: event.description,
              image: event.image,
            },
          ];
          // otherwise, just add another event to that date
        } else {
          tempDateSplitEvents[event.date].push({
            venue: event.venue,
            link: event.link,
            description: event.description,
            image: event.image,
          });
        }
      });
      setDateSplitEvents(tempDateSplitEvents);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-8xl text-center bg-gradient-to-r bg-clip-text text-transparent font-bold from-pink-500 to-blue-500">Nights out in NYC</h1>
        <p className="text-center my-6">
          Always have options on your nights out.
        </p>
        <EventGrid events={dateSplitEvents}></EventGrid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
