import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Section from "../components/Section";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-8xl">Nights out in NYC</h1>
        <p className={styles.description}>
          Always have options on your nights out.
        </p>
        <Section date="Friday December 2"></Section>
        <Section date="Saturday December 3"></Section>
        <Section date="Sunday December 4"></Section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
